SELECT * FROM customer_behavior.customer;


###1. Revenue by Gender – Compared total revenue generated by male vs. female customers.
SELECT 
    gender, SUM(purchase_amount_usd) total_revenue
FROM
    customer
GROUP BY gender;

###2. High-Spending Discount Users – Identified customers who used discounts but still spent above the average purchase amount
SELECT 
    customer_id, purchase_amount_usd
FROM
    customer
WHERE
    purchase_amount_usd > (SELECT 
            AVG(purchase_amount_usd)
        FROM
            customer)
        AND discount_applied = 'Yes'
;

###3. Top 5 Products by Rating – Found products with the highest average review ratings.
SELECT item_purchased product, ROUND(AVG(review_rating),2) average_rating 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


###4. Shipping Type Comparison – Compared average purchase amounts between Standard and Express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount_usd),2) average_purchase_amount
FROM customer
WHERE shipping_type='Standard' or shipping_type='Express'
GROUP BY shipping_type;


###5. Subscribers vs. Non-Subscribers – Compared average spend and total revenue across subscription status.
SELECT 
    subscription_status,
    COUNT(customer_id) total_customer,
    ROUND(AVG(purchase_amount_usd), 2) avg_spent,
    SUM(purchase_amount_usd) total_revenue
FROM
    customer
GROUP BY subscription_status;

##6. Discount-Dependent Products – Identified 5 products with the highest percentage of discounted purchases
SELECT 
    item_purchased product,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS percentage_discounted_purchases
FROM
    customer
GROUP BY item_purchased
ORDER BY percentage_discounted_purchases DESC
LIMIT 5;

###7. Customer Segmentation – Classified customers into New, Returning, and Loyal segments based on purchase history. Show the count of each segment
WITH segmentation AS (SELECT 
	customer_id, previous_purchases,
	CASE
		WHEN previous_purchases in (0,1) THEN "New"
        WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
        ELSE "Loyal"
	END AS customer_segment
FROM customer)

SELECT customer_segment, COUNT(*) number_of_customers
FROM segmentation
GROUP BY customer_segment;

###8. Top 3 Products per Category – Listed the most purchased products within each category.
WITH 
	products_of_each_category AS(
		SELECT 
			category, 
			item_purchased product, 
			COUNT(*) number_of_purchased
		FROM customer
		GROUP BY category, item_purchased
		ORDER BY category,item_purchased
        ),
	ranking AS(
        SELECT 
			*, 
			RANK() OVER (PARTITION BY category ORDER BY number_of_purchased DESC) ranking_in_each_category
		FROM products_of_each_category)
    
SELECT category, product, number_of_purchased
FROM ranking
WHERE ranking_in_each_category IN (1,2,3)
;


##9. Revenue by Age Group – Calculated total revenue contribution of each age group
SELECT 
    age_group, SUM(purchase_amount_usd) total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC
;

##10 — Customer percentile / top spenders
##Rank all customers by purchase amount and divide them into spending quartiles. How does subscription status differ across the four quartiles?
WITH customer_quartiles AS (
    SELECT
        customer_id,
        purchase_amount_usd,
        subscription_status,
        NTILE(4) OVER (
            ORDER BY purchase_amount_usd DESC
        ) AS spending_quartile
    FROM customer
)

SELECT 
    spending_quartile AS quartile,
    COUNT(*) AS customers,
    SUM(CASE 
        WHEN subscription_status = 'Yes' THEN 1
        ELSE 0
    END) AS subscribers, 
    AVG(purchase_amount_usd) AS avg_purchase
FROM customer_quartiles
GROUP BY spending_quartile
ORDER BY spending_quartile;



